# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "843c9251884878b01a8d3b4c42ca9ad8"
application_url = "https://example.com"
embedded = true
name = "billing-address-validator"

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[build]
automatically_update_urls_on_dev = true
